param(
  [ValidateSet('all', 'backend', 'frontend', 'uniapp-h5', 'uniapp-weixin')]
  [string]$Component = 'all',
  [switch]$SkipInstall
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$scriptPath = $PSCommandPath
if (-not $scriptPath) {
  $scriptPath = $MyInvocation.MyCommand.Path
}

$repoRoot = $PSScriptRoot
if (-not $repoRoot) {
  $repoRoot = Split-Path -Parent $scriptPath
}

function Assert-CommandAvailable {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Name
  )

  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "Required command '$Name' was not found in PATH."
  }
}

function Get-PowerShellExecutable {
  $currentProcess = Get-Process -Id $PID
  if ($currentProcess.Path) {
    return $currentProcess.Path
  }

  foreach ($candidate in @('pwsh', 'powershell')) {
    $command = Get-Command $candidate -ErrorAction SilentlyContinue
    if ($command) {
      return $command.Source
    }
  }

  throw 'Could not locate a PowerShell executable to launch child windows.'
}

function Ensure-Directory {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path
  )

  if (-not (Test-Path -LiteralPath $Path)) {
    New-Item -ItemType Directory -Path $Path -Force | Out-Null
  }
}

function Ensure-BackendEnv {
  $backendDir = Join-Path $repoRoot 'backend'
  $envFile = Join-Path $backendDir '.env'

  Ensure-Directory (Join-Path $backendDir 'data')
  Ensure-Directory (Join-Path $backendDir 'logs')

  if (Test-Path -LiteralPath $envFile) {
    return
  }

  $envContent = @"
# Auto-generated by start.ps1 for local development.
SERVER_HOST=127.0.0.1
SERVER_PORT=18080
SERVER_MODE=debug
SWAGGER_AUTO_UPDATE=false

DB_DRIVER=sqlite
DB_SQLITE_PATH=./data/gohotel.db
DB_MAX_IDLE_CONNS=10
DB_MAX_OPEN_CONNS=100

JWT_SECRET=dev-secret-key
JWT_EXPIRE_TIME=24h

REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_DB=0

SECRETID=
SECRETKEY=
COS_BASE_URL=
COS_BUCKET_NAME=

WECHAT_APP_ID=
WECHAT_APP_SECRET=

LOG_LEVEL=debug
LOG_FILENAME=logs/app.log
LOG_MAX_SIZE=100
LOG_MAX_BACKUPS=3
LOG_MAX_AGE=7
LOG_COMPRESS=false
LOG_CONSOLE=true
"@

  Set-Content -LiteralPath $envFile -Value $envContent -Encoding UTF8
  Write-Host 'Created backend/.env for local SQLite development.'
}

function Ensure-NpmDependencies {
  param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectDir,
    [Parameter(Mandatory = $true)]
    [string]$Label
  )

  if ($SkipInstall) {
    return
  }

  $nodeModulesDir = Join-Path $ProjectDir 'node_modules'
  if (Test-Path -LiteralPath $nodeModulesDir) {
    return
  }

  Write-Host "Installing npm dependencies for $Label..."
  Push-Location $ProjectDir
  try {
    & npm install
    if ($LASTEXITCODE -ne 0) {
      throw "npm install failed for $Label."
    }
  }
  finally {
    Pop-Location
  }
}

function Start-ComponentWindow {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Name
  )

  $psExe = Get-PowerShellExecutable
  $arguments = "-NoExit -ExecutionPolicy Bypass -File `"$scriptPath`" -Component $Name"

  if ($SkipInstall) {
    $arguments += ' -SkipInstall'
  }

  $process = Start-Process -FilePath $psExe -ArgumentList $arguments -WorkingDirectory $repoRoot -PassThru
  Write-Host "Started $Name in a new window (PID $($process.Id))."
}

function Start-Backend {
  Assert-CommandAvailable 'go'
  Ensure-BackendEnv

  $backendDir = Join-Path $repoRoot 'backend'
  Push-Location $backendDir
  try {
    Write-Host 'Starting backend on http://127.0.0.1:18080 ...'
    & go run cmd/server/main.go
    if ($LASTEXITCODE -ne 0) {
      throw 'Backend failed to start.'
    }
  }
  finally {
    Pop-Location
  }
}

function Start-Frontend {
  Assert-CommandAvailable 'npm'

  $frontendDir = Join-Path $repoRoot 'frontend'
  Ensure-NpmDependencies -ProjectDir $frontendDir -Label 'frontend'

  Push-Location $frontendDir
  try {
    $env:UMI_APP_API_BASE_URL = 'http://127.0.0.1:18080'
    Write-Host 'Starting frontend on http://127.0.0.1:8000 ...'
    & npm run start:dev
    if ($LASTEXITCODE -ne 0) {
      throw 'Frontend failed to start.'
    }
  }
  finally {
    Pop-Location
  }
}

function Start-Uniapp {
  param(
    [Parameter(Mandatory = $true)]
    [string]$ScriptName
  )

  Assert-CommandAvailable 'npm'

  $uniappDir = Join-Path $repoRoot 'uniapp'
  Ensure-NpmDependencies -ProjectDir $uniappDir -Label 'uniapp'

  Push-Location $uniappDir
  try {
    Write-Host "Starting uniapp with npm run $ScriptName ..."
    & npm run $ScriptName
    if ($LASTEXITCODE -ne 0) {
      throw "uniapp script '$ScriptName' failed."
    }
  }
  finally {
    Pop-Location
  }
}

switch ($Component) {
  'all' {
    Assert-CommandAvailable 'go'
    Assert-CommandAvailable 'npm'
    Ensure-BackendEnv

    Start-ComponentWindow -Name 'backend'
    Start-ComponentWindow -Name 'frontend'

    Write-Host ''
    Write-Host 'Dev environment is starting in two new windows:'
    Write-Host '  Backend : http://127.0.0.1:18080'
    Write-Host '  Frontend: http://127.0.0.1:8000'
    Write-Host ''
    Write-Host 'Single component examples:'
    Write-Host '  .\start.ps1 -Component backend'
    Write-Host '  .\start.ps1 -Component frontend'
    Write-Host '  .\start.ps1 -Component uniapp-h5'
  }
  'backend' {
    Start-Backend
  }
  'frontend' {
    Start-Frontend
  }
  'uniapp-h5' {
    Start-Uniapp -ScriptName 'dev:h5'
  }
  'uniapp-weixin' {
    Start-Uniapp -ScriptName 'dev:mp-weixin'
  }
}
