export default [
  {
    path: '/user',
    layout: false,
    routes: [{ name: '登录', path: '/user/login', component: './user/login' }],
  },
  {
    path: '/welcome',
    name: '运营控制台',
    icon: 'dashboard',
    component: './Welcome',
  },
  {
    path: '/hotel-front',
    name: '前台接待',
    icon: 'carryOut',
    routes: [
      { path: '/hotel-front', redirect: '/hotel-front/check-in' },
      {
        name: '客人办理入住',
        icon: 'login',
        path: '/hotel-front/check-in',
        component: './hotel-front/check-in',
      },
      {
        name: '客人办理退房',
        icon: 'logout',
        path: '/hotel-front/check-out',
        component: './hotel-front/check-out',
      },
    ],
  },
  {
    name: '订单与账务',
    icon: 'schedule',
    path: '/order-manage',
    component: './order-manage',
  },
  {
    path: '/room-manage',
    name: '房态运维',
    icon: 'appstore',
    routes: [
      { path: '/room-manage', redirect: '/room-manage/list' },
      {
        name: '房间列表',
        icon: 'unorderedList',
        path: '/room-manage/list',
        component: './room-manage',
      },
      {
        name: '房型分类',
        icon: 'tags',
        path: '/room-manage/category',
        component: './room-manage/room-category',
      },
      {
        name: '房间可视化',
        icon: 'project',
        path: '/room-manage/room-visualization',
        component: './room-manage/room-visualization',
      },
      {
        name: '房态库存矩阵',
        icon: 'barcode',
        path: '/room-manage/inventory',
        component: './inventory-manage',
      },
    ],
  },
  {
    name: '价格与收益',
    icon: 'lineChart',
    path: '/pricing-manage',
    component: './pricing-manage',
  },
  {
    name: '营销活动',
    icon: 'gift',
    path: '/activity-manage',
    component: './activity-manage',
  },
  {
    name: '公告与提醒',
    icon: 'notification',
    path: '/notice-manage',
    component: './notice-manage',
  },
  {
    path: '/work-order',
    name: '服务与工单',
    icon: 'tool',
    routes: [
      { path: '/work-order', redirect: '/work-order/repair' },
      {
        name: '维修记录',
        icon: 'tool',
        path: '/work-order/repair',
        component: './work-order-manage/repair',
      },
      {
        name: '清洁任务',
        icon: 'rest',
        path: '/work-order/cleaning',
        component: './work-order-manage/cleaning',
      },
    ],
  },
  {
    name: '后台用户',
    icon: 'team',
    path: '/user-manage',
    component: './user-manage',
  },
  {
    name: '操作日志',
    icon: 'fileSearch',
    path: '/log-manage',
    component: './log-manage',
  },
  {
    name: '系统设置',
    icon: 'setting',
    path: '/system-setting',
    component: './system-setting',
  },
  { path: '/profile', component: './profile' },
  { path: '/', redirect: '/welcome' },
  { path: '*', layout: false, component: './404' },
];
